import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, Sparkles, Target } from "lucide-react";

type Mode = "tradicional" | "inteligente";
type Props = { onClose: () => void };
const brl = (n: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(n);
const numeric = (v: string) => Math.max(0, Number(v.replace(",", ".")) || 0);
const box = "rounded-3xl border border-border p-5";
const field = "mt-2 w-full rounded-2xl border border-border bg-background px-4 py-3 outline-none focus:border-[#4B2CFF]";
export default function CriarMeta({ onClose }: Props) {
  const [mode, setMode] = useState<Mode | null>(null);
  const [step, setStep] = useState(1);
  const [name, setName] = useState("Meu notebook novo");
  const [category, setCategory] = useState("Tecnologia");
  const [target, setTarget] = useState(6000);
  const [saved, setSaved] = useState(500);
  const [months, setMonths] = useState(6);
  const [contribution, setContribution] = useState(700);
  const [frequency, setFrequency] = useState("Mensal");
  const [account, setAccount] = useState("Nubank");
  const [remind, setRemind] = useState(true);
  const [radar, setRadar] = useState(true);
  const [strategy, setStrategy] = useState("equilibrado");
  const [consider, setConsider] = useState([true, true, true, true]);
  const [opportunities, setOpportunities] = useState(false);
  const [finished, setFinished] = useState(false);
  const remaining = Math.max(0, target - saved);
  const percent = target > 0 ? Math.min(100, saved / target * 100) : 0;
  const perMonth = months ? remaining / months : 0;
  const capacity = Math.max(0, 5200 - 4100 - 400);
  const strategies = [
    { id: "rapido", label: "Mais rápido", amount: Math.ceil(capacity * 1.2 / 50) * 50, desc: "Exige cortes adicionais no orçamento" },
    { id: "equilibrado", label: "Equilibrado", amount: capacity, desc: "Usa a capacidade mensal estimada" },
    { id: "tranquilo", label: "Mais tranquilo", amount: 400, desc: "Preserva maior margem financeira" },
  ];
  const chosen = strategies.find(x => x.id === strategy)!;
  const estimated = chosen.amount > 0 ? Math.ceil(remaining / chosen.amount) : 0;
  const maxStep = mode === "inteligente" ? 4 : 3;
  const next = () => setStep(s => Math.min(maxStep, s + 1));
  const back = () => step === 1 ? setMode(null) : setStep(s => s - 1);
  const action = (label: string, fn: () => void, disabled = false) => <button disabled={disabled} onClick={fn} className="flex w-full items-center justify-center gap-2 rounded-full bg-[#171717] px-5 py-3 font-semibold text-white disabled:opacity-40">{label}<ArrowRight size={18}/></button>;
  const line = (label: string, value: string) => <div className="flex items-center justify-between gap-3 py-2"><span className="text-muted-foreground">{label}</span><strong className="text-right">{value}</strong></div>;
  const progress = <div className="mt-5 flex gap-1.5">{Array.from({length:maxStep}, (_,i)=><span key={i} className={`h-1.5 flex-1 rounded-full ${i < step ? "bg-[#4B2CFF]" : "bg-muted"}`}/>)}</div>;
  if (finished) return <section className={box}><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-[#F1EDFF] text-[#4B2CFF]"><Check size={32}/></div><h2 className="mt-5 text-center text-2xl font-bold">Sua meta está planejada!</h2><p className="mt-2 text-center text-muted-foreground">Prévia de {name}, sem salvar no aplicativo.</p><div className="mt-5 rounded-2xl bg-muted p-4">{line("Objetivo",brl(target))}{line("Já reservado",brl(saved))}{line("Aporte sugerido",brl(mode==="inteligente"?chosen.amount:contribution))}{line("Prazo estimado",`${mode==="inteligente"?estimated:Math.ceil(remaining/Math.max(1,frequency==="Semanal"?contribution*52/12:frequency==="Quinzenal"?contribution*26/12:contribution))} meses`)}</div><p className="my-4 text-xs text-muted-foreground">Simulação: nenhum dinheiro foi movimentado e nenhum dado foi gravado.</p>{action("Criar outra meta",()=>{setFinished(false);setMode(null);setStep(1)})}<button onClick={onClose} className="mt-3 w-full rounded-full border p-3">Voltar ao Patrimônio</button></section>;
  if (!mode) return <section className={box}><div className="flex items-center justify-between"><h2 className="text-2xl font-bold">Criar nova meta</h2><button onClick={onClose} aria-label="Fechar">✕</button></div><p className="mt-2 text-muted-foreground">Como você prefere planejar sua próxima conquista?</p>{([["tradicional","Meta","Você define o planejamento, prazo e aportes.",Target],["inteligente","Meta Inteligente","O FINNOS analisa seus dados e sugere estratégias viáveis.",Sparkles]] as const).map(([id,label,desc,Icon])=><button key={id} onClick={()=>{setMode(id);setStep(1)}} className="mt-4 flex w-full items-start gap-3 rounded-3xl border p-5 text-left hover:border-[#4B2CFF]"><Icon className="shrink-0 text-[#4B2CFF]"/><span><strong className="block text-lg">{label}</strong><span className="text-sm text-muted-foreground">{desc}</span></span><ArrowRight className="ml-auto shrink-0"/></button>)}<p className="mt-4 text-xs text-muted-foreground">Fluxos demonstrativos: a persistência e a análise financeira real serão integradas depois.</p></section>;
  return <section className={box}><div className="flex items-center justify-between gap-2"><div><p className="text-xs font-semibold text-[#4B2CFF]">FINNOS · METAS</p><h2 className="mt-2 text-2xl font-bold">{mode==="inteligente"?["Qual é sua conquista?","Análise inteligente","Seu planejamento","Finalizar meta"][step-1]:["Nova meta","Planejamento","Revisar meta"][step-1]}</h2><p className="mt-1 text-sm text-muted-foreground">{mode==="inteligente"?"Meta Inteligente":"Meta tradicional"} · Etapa {step} de {maxStep}</p></div>{mode==="inteligente"?<Sparkles className="text-[#4B2CFF]"/>:<Target className="text-[#4B2CFF]"/>}</div>{progress}
  {step===1&&<div className="mt-6 space-y-4 rounded-3xl bg-[#F7F5FF] p-4 text-[#171717] dark:bg-[#241A48] dark:text-white"><h3 className="font-bold">{mode==="inteligente"?"Conte ao FINNOS seu objetivo":"O que você quer conquistar?"}</h3><label className="block text-sm">Nome da meta<input className={field} value={name} onChange={e=>setName(e.target.value)}/></label><label className="block text-sm">Categoria<select className={field} value={category} onChange={e=>setCategory(e.target.value)}>{["Tecnologia","Viagem","Casa","Educação","Saúde","Reserva","Outros"].map(x=><option key={x}>{x}</option>)}</select></label><label className="block text-sm">Valor do objetivo (R$)<input className={field} type="number" min="1" value={target} onChange={e=>setTarget(numeric(e.target.value))}/></label><label className="block text-sm">Quanto já tem guardado? (R$)<input className={field} type="number" min="0" value={saved} onChange={e=>setSaved(Math.min(target,numeric(e.target.value)))}/></label>{mode==="inteligente"&&<><div className="flex justify-between"><strong>Quando gostaria de conquistar?</strong><strong className="text-[#4B2CFF]">{months} meses</strong></div><input className="w-full accent-[#4B2CFF]" type="range" min="1" max="36" value={months} onChange={e=>setMonths(+e.target.value)}/></>}</div>}
  {step===1&&<div className="mt-4 rounded-2xl bg-muted p-4">{line("Progresso inicial",percent.toFixed(1).replace(".",",")+"%")}<div className="h-2 rounded-full bg-background"><div className="h-full rounded-full bg-[#4B2CFF]" style={{width:`${percent}%`}}/></div>{line("Falta conquistar",brl(remaining))}{mode==="inteligente"&&line("Necessário no prazo",brl(perMonth)+"/mês")}</div>}
  {mode==="tradicional"&&step===2&&<div className="mt-6 space-y-5"><div className="flex justify-between"><strong>Quando deseja conquistar?</strong><strong className="text-[#4B2CFF]">{months} meses</strong></div><input className="w-full accent-[#4B2CFF]" type="range" min="1" max="36" value={months} onChange={e=>setMonths(+e.target.value)}/><div className="rounded-3xl bg-[#F7F5FF] p-4 text-[#171717]"><p>Para alcançar no prazo escolhido</p><p className="mt-2 text-3xl font-bold text-[#4B2CFF]">{brl(perMonth)}<span className="text-base"> / mês</span></p></div><label className="block">Quanto pretende guardar por aporte? (R$)<input className={field} type="number" min="1" value={contribution} onChange={e=>setContribution(numeric(e.target.value))}/></label><div><p>Frequência dos aportes</p>{["Semanal","Quinzenal","Mensal"].map(x=><label key={x} className="mt-2 flex gap-2"><input type="radio" checked={frequency===x} onChange={()=>setFrequency(x)}/>{x}</label>)}</div><label className="block">Conta de referência<select className={field} value={account} onChange={e=>setAccount(e.target.value)}>{["Nubank","Inter","Bradesco","Itaú","Outra"].map(x=><option key={x}>{x}</option>)}</select></label><label className="flex gap-2"><input type="checkbox" checked={remind} onChange={e=>setRemind(e.target.checked)}/>Lembrar de guardar dinheiro</label><div className="rounded-2xl border p-4"><strong>Previsão com seus aportes</strong><p className="mt-2 text-2xl font-bold">{Math.ceil(remaining/Math.max(1,frequency==="Semanal"?contribution*52/12:frequency==="Quinzenal"?contribution*26/12:contribution))} meses</p><p className="text-sm text-muted-foreground">Estimativa sem rendimentos.</p></div></div>}
  {mode==="inteligente"&&step===2&&<div className="mt-6 space-y-3"><div className="rounded-2xl bg-[#F7F5FF] p-4 text-[#171717]"><strong>FINNOS · Análise inteligente</strong><p className="mt-2 text-sm">Na versão real, o FINNOS analisará apenas dados financeiros autorizados.</p></div><h3 className="font-bold">O que considerar no planejamento?</h3>{["Receitas e despesas","Parcelas e assinaturas","Reserva financeira","Outras metas"].map((x,i)=><label key={x} className="flex items-center justify-between rounded-2xl border p-4"><span>{x}</span><input type="checkbox" checked={consider[i]} onChange={e=>setConsider(a=>a.map((v,j)=>j===i?e.target.checked:v))}/></label>)}<div className="rounded-2xl border p-4"><div className="flex justify-between"><strong>Prévia ilustrativa</strong><span className="text-xs">Dados fictícios</span></div>{line("Receitas mensais",brl(5200))}{line("Despesas e compromissos",brl(4100))}{line("Margem de segurança",brl(400))}<hr/>{line("Capacidade estimada",brl(capacity)+"/mês")}</div></div>}
  {mode==="inteligente"&&step===3&&<div className="mt-6 space-y-4"><div className="rounded-2xl bg-[#F7F5FF] p-4 text-[#171717]"><strong>Descoberta FINNOS</strong><p className="mt-2 text-sm">Com capacidade ilustrativa de {brl(capacity)}/mês, a meta levaria aproximadamente {Math.ceil(remaining/capacity)} meses. Para {months} meses, seriam necessários {brl(perMonth)}/mês.</p></div><h3 className="text-xl font-bold">Escolha sua estratégia</h3>{strategies.map(x=><button key={x.id} onClick={()=>setStrategy(x.id)} className={`w-full rounded-3xl border p-4 text-left ${strategy===x.id?"border-[#4B2CFF] bg-[#F7F5FF] text-[#171717]":"border-border"}`}><div className="flex justify-between"><strong>{x.label}</strong>{strategy===x.id&&<Check className="text-[#4B2CFF]"/>}</div><div className="mt-2 flex justify-between gap-2"><div><strong className="text-2xl">{Math.ceil(remaining/x.amount)} meses</strong><p className="text-xs text-muted-foreground">{x.desc}</p></div><strong>{brl(x.amount)}/mês</strong></div></button>)}<button onClick={()=>setOpportunities(v=>!v)} className="w-full rounded-2xl border p-4 text-left">Onde posso economizar? {opportunities?"⌃":"⌄"}</button>{opportunities&&<div className="rounded-2xl bg-muted p-4 text-sm">{line("Assinaturas pouco utilizadas","R$ 45/mês")}{line("Alimentação fora","R$ 120/mês")}{line("Compras não essenciais","R$ 85/mês")}<p className="mt-2 text-xs text-muted-foreground">Exemplos fictícios, não são despesas identificadas na sua conta.</p></div>}</div>}
  {step===maxStep&&<div className="mt-6 space-y-4"><div className="rounded-3xl bg-[#F7F5FF] p-5 text-[#171717]"><h3 className="text-lg font-bold">{name}</h3><p className="text-sm">{category} · {mode==="inteligente"?"Meta Inteligente":"Meta tradicional"}</p><div className="mt-4">{line("Objetivo",brl(target))}{line("Já guardado",brl(saved))}{line("Progresso inicial",percent.toFixed(1).replace(".",",")+"%")}{line(mode==="inteligente"?"Estratégia":"Prazo desejado",mode==="inteligente"?chosen.label:`${months} meses`)}{line("Aporte",brl(mode==="inteligente"?chosen.amount:contribution))}</div></div><label className="block">Conta para guardar o dinheiro<select className={field} value={account} onChange={e=>setAccount(e.target.value)}>{["Nubank","Inter","Bradesco","Itaú","Outra"].map(x=><option key={x}>{x}</option>)}</select></label>{mode==="inteligente"?<><label className="flex gap-2"><input type="checkbox" checked={radar} onChange={e=>setRadar(e.target.checked)}/>Receber alertas pelo Radar FINNOS</label><div className="rounded-2xl border p-4"><strong>Planejamento adaptativo</strong><p className="mt-2 text-sm text-muted-foreground">Na versão real, o FINNOS poderá recalcular os prazos quando sua situação financeira mudar.</p></div></>:<p className="rounded-2xl border p-4 text-sm">Você poderá transformar esta meta em inteligente futuramente.</p>}</div>}
  <div className="mt-6 flex gap-3"><button onClick={back} aria-label="Voltar" className="rounded-full border px-5"><ArrowLeft/></button>{action(step===maxStep?"Concluir simulação":mode==="inteligente"&&step===1?"Analisar minha meta":step===maxStep-1?"Revisar planejamento":"Continuar",step===maxStep?()=>setFinished(true):next,step===1&&(!name.trim()||target<=0||saved>target)||mode==="tradicional"&&step===2&&contribution<=0)}</div><p className="mt-4 text-center text-xs text-muted-foreground">Prévia funcional. Nenhum dado será salvo nem movimentado.</p></section>;
}
