"""Radar models — dynamic financial signals generated by the FINNOS engine."""
from typing import List, Literal, Optional
from pydantic import BaseModel

RadarType = Literal["risk", "deviation", "information", "opportunity"]
RadarSeverity = Literal["normal", "medium", "high", "critical"]

class RadarSignalOut(BaseModel):
    id: str
    type: RadarType
    severity: RadarSeverity
    title: str
    description: str
    metric: Optional[str] = None
    radar_position: int
    score: float
    related_entity_type: Optional[str] = None
    related_entity_id: Optional[str] = None
    expires_at: Optional[str] = None

class RadarOut(BaseModel):
    items: List[RadarSignalOut]
    count: int
