import { Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis } from "recharts";
import type { FinnVisual } from "@/lib/aiConversations";

export function AiVisual({ visual }: { visual: FinnVisual }) {
  return <div className="mt-3 grid gap-2">
    {visual.title?<p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{visual.title}</p>:null}
    {visual.metrics?<div className="grid grid-cols-3 gap-2">{visual.metrics.map(x=><div key={x.label} className="rounded-xl bg-muted/70 p-3"><p className="text-[11px] text-muted-foreground">{x.label}</p><p className={x.tone==="positive"?"mt-1 font-semibold text-emerald-500":x.tone==="negative"?"mt-1 font-semibold text-red-500":"mt-1 font-semibold"}>{x.value}</p></div>)}</div>:null}
    {visual.chart?.type==="line"?<div className="h-44 rounded-xl bg-muted/30 p-2"><ResponsiveContainer width="100%" height="100%"><LineChart data={visual.chart.data}><XAxis dataKey="name" tickLine={false} axisLine={false} fontSize={11}/><Tooltip/><Line type="monotone" dataKey="value" name={visual.chart.valueLabel} stroke="currentColor" strokeWidth={2.5} dot={false}/>{visual.chart.data.some(x=>x.secondary!==undefined)?<Line type="monotone" dataKey="secondary" name={visual.chart.secondaryLabel} stroke="var(--muted-foreground)" strokeWidth={2} dot={false}/>:null}</LineChart></ResponsiveContainer></div>:null}
    {visual.chart?.type==="donut"?<div className="flex items-center gap-3 rounded-xl bg-muted/30 p-2"><div className="h-36 w-36 shrink-0"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={visual.chart.data} dataKey="value" nameKey="name" innerRadius={38} outerRadius={58} paddingAngle={2}>{visual.chart.data.map((_,i)=><Cell key={i} fill={["#4B2CFF","#5B35FF","#7C63FF","#9B8AFF","#B8ADFF","#D4CEFF"][i%6]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="min-w-0 space-y-1">{visual.chart.data.slice(0,5).map((x,i)=><div key={x.name} className="flex items-center gap-2 text-xs"><span className="h-2 w-2 rounded-full" style={{background:["#4B2CFF","#5B35FF","#7C63FF","#9B8AFF","#B8ADFF"][i%5]}}/><span className="truncate">{x.name}</span></div>)}</div></div>:null}
    {visual.items?<div className="overflow-hidden rounded-xl border border-border">{visual.items.map((x,i)=><div key={x.label+i} className="flex items-center justify-between gap-3 border-b border-border/70 px-3 py-2.5 last:border-b-0"><div className="min-w-0"><p className="truncate font-medium">{x.label}</p>{x.detail?<p className="text-xs text-muted-foreground">{x.detail}</p>:null}</div><strong className="shrink-0">{x.value}</strong></div>)}</div>:null}
  </div>;
}
